name: Automatic push git-action
run-name: ${{ github.actor }} Melakukan push dockerhub
on: [push]
jobs:
  BUILD-AND-PUSH-IMAGE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and tag image
        run: docker build . --file Dockerfile --tag oyiiro/uas:v3
      - name: push image to docker hub
        run: docker login -u oyiiro -p ${{secrets.DOCKER_ASEP}} && docker push oyiiro/uas:v3